// Command docgen keeps public examples and CLI defaults synchronized with code.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/ebubekiryigit/blackbox-ebpf/internal/cli"
	"github.com/ebubekiryigit/blackbox-ebpf/internal/config"
)

func main() {
	check := flag.Bool("check", false, "fail if generated artifacts are stale")
	flag.Parse()
	example, err := config.ExampleYAML()
	must(err)
	outputs := map[string][]byte{
		"config.example.yml": append([]byte("# Generated by make docs; copy to config.yml before customizing.\n# Compiled defaults → this file → explicitly provided CLI flags.\n# Every setting is optional. Restart the daemon after changes.\n\n"), example...),
		"docs/cli.md":        []byte(reference()),
	}
	mod, err := os.ReadFile("go.mod")
	must(err)
	match := regexp.MustCompile(`(?m)^go (\S+)$`).FindSubmatch(mod)
	if len(match) != 2 {
		must(fmt.Errorf("go.mod has no Go version"))
	}
	for _, path := range []string{"Dockerfile", "Dockerfile.tools"} {
		docker, err := os.ReadFile(path)
		must(err)
		outputs[path] = regexp.MustCompile(`(?m)^ARG GO_VERSION=\S+$`).ReplaceAll(docker, []byte("ARG GO_VERSION="+string(match[1])))
	}
	toolMod, err := os.ReadFile("tools/licenses/go.mod")
	must(err)
	outputs["tools/licenses/go.mod"] = regexp.MustCompile(`(?m)^go \S+$`).ReplaceAll(toolMod, []byte("go "+string(match[1])))
	for path, want := range outputs {
		if *check {
			got, err := os.ReadFile(path)
			must(err)
			if !bytes.Equal(got, want) {
				must(fmt.Errorf("%s is stale; run make docs", path))
			}
		} else {
			must(writeAtomic(path, want))
		}
	}
}

// Replace generated files atomically. Existing file bind mounts keep their old
// inode until the container is recreated instead of receiving half-written data.
func writeAtomic(path string, content []byte) error {
	f, err := os.CreateTemp(".", ".blackbox-doc-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if err = f.Chmod(0644); err == nil {
		_, err = f.Write(content)
	}
	closeErr := f.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	return os.Rename(f.Name(), path)
}
func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func reference() string {
	root := cli.New()
	var b strings.Builder
	b.WriteString("<!-- Generated by make docs; edit CLI/config source, then regenerate. -->\n# CLI reference\n\nRecording and config commands accept `--config PATH` to read one explicit YAML file.\nExplicit flags override file values only when provided. Status and snapshot use the\nrunning daemon through its control socket and do not reload that file. See\n[configuration](configuration.md) for precedence, validation and resource budgets.\n`--help` is available on every command; `--version` and `version` print the\napplication build version.\n\n")
	b.WriteString("## Global flags\n\nRecording settings belong to `daemon` and `capture`. The socket is a CLI-only\nendpoint choice for `daemon`, `status`, and `snapshot`; timeout is also a YAML\nsetting. Offline analysis only needs presentation options. `config check` and\n`config show` accept YAML setting overrides for validation.\n\n")
	table(&b, root.PersistentFlags())
	var commands func(*cobra.Command)
	commands = func(parent *cobra.Command) {
		for _, cmd := range parent.Commands() {
			if cmd.Hidden {
				continue
			}
			fmt.Fprintf(&b, "## `%s`\n\n%s.\n\n```sh\n%s\n```\n\n", cmd.CommandPath(), cmd.Short, usage(cmd))
			table(&b, cmd.LocalNonPersistentFlags())
			commands(cmd)
		}
	}
	commands(root)
	return strings.TrimRight(b.String(), "\n") + "\n"
}
func usage(cmd *cobra.Command) string { return cmd.Parent().CommandPath() + " " + cmd.Use }
func table(b *strings.Builder, flags *pflag.FlagSet) {
	if flags.NFlag() == 0 && !flags.HasFlags() {
		return
	}
	b.WriteString("| Flag | Default | Purpose |\n| --- | --- | --- |\n")
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name += ", -" + f.Shorthand
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", name, escape(f.DefValue), escape(f.Usage))
	})
	b.WriteString("\n")
}
func escape(s string) string { return strings.NewReplacer("|", "\\|", "\n", " ").Replace(s) }
