// Command bpfabi generates kernel histogram constants from the durable model.
package main

import (
	"fmt"
	"os"

	"github.com/ebubekiryigit/blackbox-ebpf/internal/model"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: bpfabi OUTPUT")
		os.Exit(1)
	}
	b := fmt.Sprintf("// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only\n// Code generated by bpfabi; DO NOT EDIT.\n#ifndef BLACKBOX_ABI_H\n#define BLACKBOX_ABI_H\n#define BLACKBOX_HISTOGRAM_BUCKETS %d\n#define BLACKBOX_HISTOGRAM_MIN_NS %dULL\n#endif\n", model.HistogramBuckets, model.HistogramMinNS)
	if err := os.WriteFile(os.Args[1], []byte(b), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
