// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// Code generated by bpfabi; DO NOT EDIT.
#ifndef BLACKBOX_ABI_H
#define BLACKBOX_ABI_H
#define BLACKBOX_HISTOGRAM_BUCKETS 11
#define BLACKBOX_HISTOGRAM_MIN_NS 1000000ULL
#define BLACKBOX_CRITICAL_DETAIL_DIVISOR 4
#endif
