// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type blockInflight struct {
	_        structs.HostLayout
	Start    uint64
	Identity struct {
		_               structs.HostLayout
		MonoNs          uint64
		LatencyNs       uint64
		CgroupId        uint64
		ProcessStartNs  uint64
		Bytes           uint64
		Pid             uint32
		Tgid            uint32
		Cpu             uint32
		Major           uint32
		Minor           uint32
		Kind            uint32
		State           uint32
		SourcePort      uint16
		DestinationPort uint16
		Family          uint16
		Operation       uint16
		Comm            [16]int8
		SourceIp        [16]uint8
		DestinationIp   [16]uint8
		_               [4]byte
	}
}

type blockStats struct {
	_                      structs.HostLayout
	Histogram              [11]uint64
	Count                  uint64
	Anomalies              uint64
	Critical               uint64
	Bytes                  uint64
	Retransmits            uint64
	Resets                 uint64
	RingFailures           uint64
	Suppressed             uint64
	TrackingFailures       uint64
	Unmatched              uint64
	BookkeepingCompletions uint64
	BudgetSecond           uint64
	BudgetUsed             uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	blockMapAggregates          = "aggregates"
	blockMapDetails             = "details"
	blockMapStarts              = "starts"
	blockProgComplete           = "complete"
	blockProgIssue              = "issue"
	blockVarCriticalThresholdNs = "critical_threshold_ns"
	blockVarDetailRate          = "detail_rate"
	blockVarPossibleCpus        = "possible_cpus"
	blockVarRqArgIndex          = "rq_arg_index"
	blockVarThresholdNs         = "threshold_ns"
)

// loadBlock returns the embedded CollectionSpec for block.
func loadBlock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BlockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load block: %w", err)
	}

	return spec, err
}

// loadBlockObjects loads block and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*blockObjects
//	*blockPrograms
//	*blockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBlockObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBlock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// blockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockSpecs struct {
	blockProgramSpecs
	blockMapSpecs
	blockVariableSpecs
}

// blockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockProgramSpecs struct {
	Complete *ebpf.ProgramSpec `ebpf:"complete"`
	Issue    *ebpf.ProgramSpec `ebpf:"issue"`
}

// blockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockMapSpecs struct {
	Aggregates *ebpf.MapSpec `ebpf:"aggregates"`
	Details    *ebpf.MapSpec `ebpf:"details"`
	Starts     *ebpf.MapSpec `ebpf:"starts"`
}

// blockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockVariableSpecs struct {
	CriticalThresholdNs *ebpf.VariableSpec `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.VariableSpec `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.VariableSpec `ebpf:"possible_cpus"`
	RqArgIndex          *ebpf.VariableSpec `ebpf:"rq_arg_index"`
	ThresholdNs         *ebpf.VariableSpec `ebpf:"threshold_ns"`
}

// blockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockObjects struct {
	blockPrograms
	blockMaps
	blockVariables
}

func (o *blockObjects) Close() error {
	return _BlockClose(
		&o.blockPrograms,
		&o.blockMaps,
	)
}

// blockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockMaps struct {
	Aggregates *ebpf.Map `ebpf:"aggregates"`
	Details    *ebpf.Map `ebpf:"details"`
	Starts     *ebpf.Map `ebpf:"starts"`
}

func (m *blockMaps) Close() error {
	return _BlockClose(
		m.Aggregates,
		m.Details,
		m.Starts,
	)
}

// blockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockVariables struct {
	CriticalThresholdNs *ebpf.Variable `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.Variable `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.Variable `ebpf:"possible_cpus"`
	RqArgIndex          *ebpf.Variable `ebpf:"rq_arg_index"`
	ThresholdNs         *ebpf.Variable `ebpf:"threshold_ns"`
}

// blockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockPrograms struct {
	Complete *ebpf.Program `ebpf:"complete"`
	Issue    *ebpf.Program `ebpf:"issue"`
}

func (p *blockPrograms) Close() error {
	return _BlockClose(
		p.Complete,
		p.Issue,
	)
}

func _BlockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed block_bpfel.o
var _BlockBytes []byte
