package sensor

// Generated bytecode is checked in; only regenerating it needs this build toolchain.
//go:generate go run ../tools/bpfabi ../../bpf/abi.h
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel -tags linux block ../../bpf/block.c -- -O2 -g -Wall -Werror
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel -tags linux sched ../../bpf/sched.c -- -O2 -g -Wall -Werror
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel -tags linux tcp ../../bpf/tcp.c -- -O2 -g -Wall -Werror
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel -tags linux oom ../../bpf/oom.c -- -O2 -g -Wall -Werror
