// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type oomStats struct {
	_                      structs.HostLayout
	Histogram              [11]uint64
	Count                  uint64
	Anomalies              uint64
	Critical               uint64
	Bytes                  uint64
	Retransmits            uint64
	Resets                 uint64
	RingFailures           uint64
	Suppressed             uint64
	TrackingFailures       uint64
	Unmatched              uint64
	BookkeepingCompletions uint64
	BudgetSecond           uint64
	BudgetUsed             uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	oomMapAggregates          = "aggregates"
	oomMapDetails             = "details"
	oomProgVictim             = "victim"
	oomVarCriticalThresholdNs = "critical_threshold_ns"
	oomVarDetailRate          = "detail_rate"
	oomVarPossibleCpus        = "possible_cpus"
	oomVarThresholdNs         = "threshold_ns"
)

// loadOom returns the embedded CollectionSpec for oom.
func loadOom() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OomBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load oom: %w", err)
	}

	return spec, err
}

// loadOomObjects loads oom and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*oomObjects
//	*oomPrograms
//	*oomMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOomObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOom()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// oomSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomSpecs struct {
	oomProgramSpecs
	oomMapSpecs
	oomVariableSpecs
}

// oomProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomProgramSpecs struct {
	Victim *ebpf.ProgramSpec `ebpf:"victim"`
}

// oomMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomMapSpecs struct {
	Aggregates *ebpf.MapSpec `ebpf:"aggregates"`
	Details    *ebpf.MapSpec `ebpf:"details"`
}

// oomVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomVariableSpecs struct {
	CriticalThresholdNs *ebpf.VariableSpec `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.VariableSpec `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.VariableSpec `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.VariableSpec `ebpf:"threshold_ns"`
}

// oomObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomObjects struct {
	oomPrograms
	oomMaps
	oomVariables
}

func (o *oomObjects) Close() error {
	return _OomClose(
		&o.oomPrograms,
		&o.oomMaps,
	)
}

// oomMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomMaps struct {
	Aggregates *ebpf.Map `ebpf:"aggregates"`
	Details    *ebpf.Map `ebpf:"details"`
}

func (m *oomMaps) Close() error {
	return _OomClose(
		m.Aggregates,
		m.Details,
	)
}

// oomVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomVariables struct {
	CriticalThresholdNs *ebpf.Variable `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.Variable `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.Variable `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.Variable `ebpf:"threshold_ns"`
}

// oomPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomPrograms struct {
	Victim *ebpf.Program `ebpf:"victim"`
}

func (p *oomPrograms) Close() error {
	return _OomClose(
		p.Victim,
	)
}

func _OomClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed oom_bpfel.o
var _OomBytes []byte
