// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux && integration

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type policytestDetailBudget struct {
	_    structs.HostLayout
	Used uint64
}

type policytestPolicyInput struct {
	_          structs.HostLayout
	Action     uint64
	Generation uint64
	Now        uint64
	Critical   uint64
}

type policytestRequestTiming struct {
	_          structs.HostLayout
	Start      uint64
	Generation uint64
	Requeued   uint64
}

type policytestStats struct {
	_                      structs.HostLayout
	Histogram              [11]uint64
	Count                  uint64
	Anomalies              uint64
	Critical               uint64
	Bytes                  uint64
	Retransmits            uint64
	Resets                 uint64
	RingFailures           uint64
	Suppressed             uint64
	DetailBudgetFailures   uint64
	TrackingFailures       uint64
	Unmatched              uint64
	BookkeepingCompletions uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	policytestMapAggregates          = "aggregates"
	policytestMapDetailBudgets       = "detail_budgets"
	policytestMapDetails             = "details"
	policytestMapTestInput           = "test_input"
	policytestMapTiming              = "timing"
	policytestProgPolicies           = "policies"
	policytestVarCriticalThresholdNs = "critical_threshold_ns"
	policytestVarDetailRate          = "detail_rate"
	policytestVarThresholdNs         = "threshold_ns"
)

// loadPolicytest returns the embedded CollectionSpec for policytest.
func loadPolicytest() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PolicytestBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load policytest: %w", err)
	}

	return spec, err
}

// loadPolicytestObjects loads policytest and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*policytestObjects
//	*policytestPrograms
//	*policytestMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPolicytestObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPolicytest()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// policytestSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policytestSpecs struct {
	policytestProgramSpecs
	policytestMapSpecs
	policytestVariableSpecs
}

// policytestProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policytestProgramSpecs struct {
	Policies *ebpf.ProgramSpec `ebpf:"policies"`
}

// policytestMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policytestMapSpecs struct {
	Aggregates    *ebpf.MapSpec `ebpf:"aggregates"`
	DetailBudgets *ebpf.MapSpec `ebpf:"detail_budgets"`
	Details       *ebpf.MapSpec `ebpf:"details"`
	TestInput     *ebpf.MapSpec `ebpf:"test_input"`
	Timing        *ebpf.MapSpec `ebpf:"timing"`
}

// policytestVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policytestVariableSpecs struct {
	CriticalThresholdNs *ebpf.VariableSpec `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.VariableSpec `ebpf:"detail_rate"`
	ThresholdNs         *ebpf.VariableSpec `ebpf:"threshold_ns"`
}

// policytestObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPolicytestObjects or ebpf.CollectionSpec.LoadAndAssign.
type policytestObjects struct {
	policytestPrograms
	policytestMaps
	policytestVariables
}

func (o *policytestObjects) Close() error {
	return _PolicytestClose(
		&o.policytestPrograms,
		&o.policytestMaps,
	)
}

// policytestMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPolicytestObjects or ebpf.CollectionSpec.LoadAndAssign.
type policytestMaps struct {
	Aggregates    *ebpf.Map `ebpf:"aggregates"`
	DetailBudgets *ebpf.Map `ebpf:"detail_budgets"`
	Details       *ebpf.Map `ebpf:"details"`
	TestInput     *ebpf.Map `ebpf:"test_input"`
	Timing        *ebpf.Map `ebpf:"timing"`
}

func (m *policytestMaps) Close() error {
	return _PolicytestClose(
		m.Aggregates,
		m.DetailBudgets,
		m.Details,
		m.TestInput,
		m.Timing,
	)
}

// policytestVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPolicytestObjects or ebpf.CollectionSpec.LoadAndAssign.
type policytestVariables struct {
	CriticalThresholdNs *ebpf.Variable `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.Variable `ebpf:"detail_rate"`
	ThresholdNs         *ebpf.Variable `ebpf:"threshold_ns"`
}

// policytestPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPolicytestObjects or ebpf.CollectionSpec.LoadAndAssign.
type policytestPrograms struct {
	Policies *ebpf.Program `ebpf:"policies"`
}

func (p *policytestPrograms) Close() error {
	return _PolicytestClose(
		p.Policies,
	)
}

func _PolicytestClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed policytest_bpfel.o
var _PolicytestBytes []byte
