// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type schedStats struct {
	_                      structs.HostLayout
	Histogram              [11]uint64
	Count                  uint64
	Anomalies              uint64
	Critical               uint64
	Bytes                  uint64
	Retransmits            uint64
	Resets                 uint64
	RingFailures           uint64
	Suppressed             uint64
	TrackingFailures       uint64
	Unmatched              uint64
	BookkeepingCompletions uint64
	BudgetSecond           uint64
	BudgetUsed             uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	schedMapAggregates          = "aggregates"
	schedMapDetails             = "details"
	schedMapRunnable            = "runnable"
	schedProgExitTask           = "exit_task"
	schedProgSwitchTask         = "switch_task"
	schedProgWakeup             = "wakeup"
	schedProgWakeupNew          = "wakeup_new"
	schedVarCriticalThresholdNs = "critical_threshold_ns"
	schedVarDetailRate          = "detail_rate"
	schedVarPossibleCpus        = "possible_cpus"
	schedVarThresholdNs         = "threshold_ns"
)

// loadSched returns the embedded CollectionSpec for sched.
func loadSched() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sched: %w", err)
	}

	return spec, err
}

// loadSchedObjects loads sched and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*schedObjects
//	*schedPrograms
//	*schedMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSchedObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSched()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// schedSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedSpecs struct {
	schedProgramSpecs
	schedMapSpecs
	schedVariableSpecs
}

// schedProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedProgramSpecs struct {
	ExitTask   *ebpf.ProgramSpec `ebpf:"exit_task"`
	SwitchTask *ebpf.ProgramSpec `ebpf:"switch_task"`
	Wakeup     *ebpf.ProgramSpec `ebpf:"wakeup"`
	WakeupNew  *ebpf.ProgramSpec `ebpf:"wakeup_new"`
}

// schedMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedMapSpecs struct {
	Aggregates *ebpf.MapSpec `ebpf:"aggregates"`
	Details    *ebpf.MapSpec `ebpf:"details"`
	Runnable   *ebpf.MapSpec `ebpf:"runnable"`
}

// schedVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedVariableSpecs struct {
	CriticalThresholdNs *ebpf.VariableSpec `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.VariableSpec `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.VariableSpec `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.VariableSpec `ebpf:"threshold_ns"`
}

// schedObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSchedObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedObjects struct {
	schedPrograms
	schedMaps
	schedVariables
}

func (o *schedObjects) Close() error {
	return _SchedClose(
		&o.schedPrograms,
		&o.schedMaps,
	)
}

// schedMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSchedObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedMaps struct {
	Aggregates *ebpf.Map `ebpf:"aggregates"`
	Details    *ebpf.Map `ebpf:"details"`
	Runnable   *ebpf.Map `ebpf:"runnable"`
}

func (m *schedMaps) Close() error {
	return _SchedClose(
		m.Aggregates,
		m.Details,
		m.Runnable,
	)
}

// schedVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSchedObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedVariables struct {
	CriticalThresholdNs *ebpf.Variable `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.Variable `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.Variable `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.Variable `ebpf:"threshold_ns"`
}

// schedPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSchedObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedPrograms struct {
	ExitTask   *ebpf.Program `ebpf:"exit_task"`
	SwitchTask *ebpf.Program `ebpf:"switch_task"`
	Wakeup     *ebpf.Program `ebpf:"wakeup"`
	WakeupNew  *ebpf.Program `ebpf:"wakeup_new"`
}

func (p *schedPrograms) Close() error {
	return _SchedClose(
		p.ExitTask,
		p.SwitchTask,
		p.Wakeup,
		p.WakeupNew,
	)
}

func _SchedClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sched_bpfel.o
var _SchedBytes []byte
