// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpStats struct {
	_                      structs.HostLayout
	Histogram              [11]uint64
	Count                  uint64
	Anomalies              uint64
	Critical               uint64
	Bytes                  uint64
	Retransmits            uint64
	Resets                 uint64
	RingFailures           uint64
	Suppressed             uint64
	TrackingFailures       uint64
	Unmatched              uint64
	BookkeepingCompletions uint64
	BudgetSecond           uint64
	BudgetUsed             uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpMapAggregates          = "aggregates"
	tcpMapDetails             = "details"
	tcpProgReceiveReset       = "receive_reset"
	tcpProgRetransmit         = "retransmit"
	tcpProgSendReset          = "send_reset"
	tcpVarCriticalThresholdNs = "critical_threshold_ns"
	tcpVarDetailRate          = "detail_rate"
	tcpVarPossibleCpus        = "possible_cpus"
	tcpVarThresholdNs         = "threshold_ns"
)

// loadTcp returns the embedded CollectionSpec for tcp.
func loadTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp: %w", err)
	}

	return spec, err
}

// loadTcpObjects loads tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpObjects
//	*tcpPrograms
//	*tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpSpecs struct {
	tcpProgramSpecs
	tcpMapSpecs
	tcpVariableSpecs
}

// tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpProgramSpecs struct {
	ReceiveReset *ebpf.ProgramSpec `ebpf:"receive_reset"`
	Retransmit   *ebpf.ProgramSpec `ebpf:"retransmit"`
	SendReset    *ebpf.ProgramSpec `ebpf:"send_reset"`
}

// tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpMapSpecs struct {
	Aggregates *ebpf.MapSpec `ebpf:"aggregates"`
	Details    *ebpf.MapSpec `ebpf:"details"`
}

// tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpVariableSpecs struct {
	CriticalThresholdNs *ebpf.VariableSpec `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.VariableSpec `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.VariableSpec `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.VariableSpec `ebpf:"threshold_ns"`
}

// tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpObjects struct {
	tcpPrograms
	tcpMaps
	tcpVariables
}

func (o *tcpObjects) Close() error {
	return _TcpClose(
		&o.tcpPrograms,
		&o.tcpMaps,
	)
}

// tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpMaps struct {
	Aggregates *ebpf.Map `ebpf:"aggregates"`
	Details    *ebpf.Map `ebpf:"details"`
}

func (m *tcpMaps) Close() error {
	return _TcpClose(
		m.Aggregates,
		m.Details,
	)
}

// tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpVariables struct {
	CriticalThresholdNs *ebpf.Variable `ebpf:"critical_threshold_ns"`
	DetailRate          *ebpf.Variable `ebpf:"detail_rate"`
	PossibleCpus        *ebpf.Variable `ebpf:"possible_cpus"`
	ThresholdNs         *ebpf.Variable `ebpf:"threshold_ns"`
}

// tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpPrograms struct {
	ReceiveReset *ebpf.Program `ebpf:"receive_reset"`
	Retransmit   *ebpf.Program `ebpf:"retransmit"`
	SendReset    *ebpf.Program `ebpf:"send_reset"`
}

func (p *tcpPrograms) Close() error {
	return _TcpClose(
		p.ReceiveReset,
		p.Retransmit,
		p.SendReset,
	)
}

func _TcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_bpfel.o
var _TcpBytes []byte
